"""Declarative schema layer — the contract an LLM (or human) fills in.

Two halves:

* :mod:`cept.schema.case`   — *input*: how a study is described.
* :mod:`cept.schema.result` — *output*: engine-agnostic results.

Nothing in this package imports an engine. The schema is pure data so it
can be validated, serialized, hashed, and reasoned about by an LLM without
OpenDSS (or any solver) being present.
"""

from cept.schema.case import (
    Assumption,
    Case,
    CaseStudy,
    CaseExperiment,
    DER,
    DynamicsEvent,
    DynamicsMonitorSignal,
    DynamicsSpec,
    EMTSpec,
    QSTSSpec,
    TimeSeriesProfile,
    HarmonicInjection,
    HarmonicsSpec,
    WECCCompositeSpec,
    ProtectionOptions,
    ProtectionRelay,
    Experiment,
    ExperimentAction,
    GridSource,
    InductionMachine,
    InverterControl,
    OpenDERSpec,
    InlineLineTotalParameters,
    Load,
    LoadFlowOptions,
    FaultOptions,
    HostingCapacityOptions,
    GicOptions,
    MachineDynamics,
    Meta,
    NetworkSpec,
    Scenario,
    SweepSpec,
    StandardsSpec,
    StudySpec,
)
from cept.schema.sld import (
    SLDEdge,
    SLDEvent,
    SLDGen,
    SLDLoad,
    SLDModel,
    SLDNode,
    SLDShunt,
)
from cept.schema.result import (
    BranchFlow,
    BusVoltage,
    ChannelSemanticDescriptor,
    DEROutput,
    DynamicsResult,
    EMTResult,
    FaultCurrent,
    FaultResult,
    FaultStudyRow,
    GICElementFlow,
    GICResult,
    HostingCapacityItem,
    HostingCapacityResult,
    LoadFlowResult,
    MonitorChannel,
    MonitorTrace,
    TimeSeriesResult,
    TimeSeriesSnapshot,
    HarmonicBusVoltage,
    HarmonicSnapshot,
    HarmonicsResult,
    ProtectionResult,
    ProtectionTrip,
    StudyResult,
    SLDSnapshot,
    ValidationItem,
    ValidationReport,
)
from cept.schema.provenance import (
    CaseProvenance,
    PowerFactoryStudyCase,
    PowerFactoryVariation,
    SourceFile,
    SourceManifest,
    TopologyEvidence,
)
from cept.schema.intake_resolution import (
    CaseInfoResolutionItem,
    CaseInfoResolutionLedger,
    ResolutionPolicy,
    ResolutionStatus,
)

__all__ = [
    "Case",
    "CaseStudy",
    "CaseExperiment",
    "Assumption",
    "Meta",
    "NetworkSpec",
    "GridSource",
    "DER",
    "InverterControl",
    "OpenDERSpec",
    "InlineLineTotalParameters",
    "Load",
    "StudySpec",
    "LoadFlowOptions",
    "FaultOptions",
    "HostingCapacityOptions",
    "GicOptions",
    "Scenario",
    "SweepSpec",
    "Experiment",
    "ExperimentAction",
    "DynamicsSpec",
    "EMTSpec",
    "DynamicsEvent",
    "QSTSSpec",
    "TimeSeriesProfile",
    "HarmonicInjection",
    "HarmonicsSpec",
    "WECCCompositeSpec",
    "ProtectionOptions",
    "ProtectionRelay",
    "MachineDynamics",
    "InductionMachine",
    "StandardsSpec",
    "BusVoltage",
    "BranchFlow",
    "ChannelSemanticDescriptor",
    "DEROutput",
    "LoadFlowResult",
    "FaultCurrent",
    "FaultResult",
    "FaultStudyRow",
    "HostingCapacityItem",
    "HostingCapacityResult",
    "DynamicsResult",
    "DynamicsMonitorSignal",
    "EMTResult",
    "MonitorTrace",
    "MonitorChannel",
    "TimeSeriesResult",
    "TimeSeriesSnapshot",
    "HarmonicBusVoltage",
    "HarmonicSnapshot",
    "HarmonicsResult",
    "ProtectionResult",
    "ProtectionTrip",
    "GICResult",
    "GICElementFlow",
    "StudyResult",
    "SLDSnapshot",
    "ValidationItem",
    "ValidationReport",
    "SLDModel",
    "SLDNode",
    "SLDEdge",
    "SLDLoad",
    "SLDGen",
    "SLDShunt",
    "SLDEvent",
    "CaseProvenance",
    "PowerFactoryStudyCase",
    "PowerFactoryVariation",
    "SourceFile",
    "SourceManifest",
    "TopologyEvidence",
    "CaseInfoResolutionItem",
    "CaseInfoResolutionLedger",
    "ResolutionPolicy",
    "ResolutionStatus",
]
